name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-go:
    name: Build Go Project
    runs-on: ubuntu-latest
    if: contains(github.event.commits.*.modified, 'go-ebitengine/')

    defaults:
      run:
        working-directory: ./go-ebitengine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

      - name: Install Dependencies
        run: go mod tidy

      - name: Static Analysis
        run: go vet ./...

      - name: Run Tests
        run: go test ./...

      - name: Build WASM
        run: GOOS=js GOARCH=wasm go build -o ../public/game.wasm

  build-rust:
    name: Build Rust Project
    runs-on: ubuntu-latest
    if: contains(github.event.commits.*.modified, 'rust-bevy/')

    defaults:
      run:
        working-directory: ./rust-bevy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Dependencies
        run: cargo fetch

      - name: Build Project
        run: cargo build --release

      - name: Run Tests
        run: cargo test

      - name: Build WASM
        run: cargo build --release --target wasm32-unknown-unknown

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-go, build-rust] # Wait for both build steps to finish

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deploy to Deno
        uses: denoland/deployctl@v1
        with:
          project: "otuff-wasm-game-36"
          entrypoint: "server.tsx"
          root: "."
