name: Go CI/CD

on:
  push:
    paths:
      - "go-ebitengine/**"
    branches:
      - main
  pull_request:
    paths:
      - "go-ebitengine/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      built: "true"

    defaults:
      run:
        working-directory: ./go-ebitengine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

      - name: Install Dependencies
        run: go mod tidy

      - name: Static Analysis
        run: go vet ./...

      - name: Run Tests
        run: go test ./...

      - name: Build WASM
        run: GOOS=js GOARCH=wasm go build -o ../public/game.wasm
